wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 80:80

wordpress_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password


phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - wordpress_db:mysql
    ports:
      - 8082:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
